"""add ondelete cascade to fks

Revision ID: b4b569877ac1
Revises: ea7d1847a2c9
Create Date: 2026-09-02 20:17:28.106370

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4b569877ac1'
down_revision: str | Sequence[str] | None = 'ea7d1847a2c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("snapshots_tracked_page_id_fkey"), "snapshots", type_="foreignkey")
    op.create_foreign_key(
        None, "snapshots", "tracked_pages", ["tracked_page_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("tracked_pages_user_id_fkey"), "tracked_pages", type_="foreignkey")
    op.create_foreign_key(
        None, "tracked_pages", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tracked_pages", type_="foreignkey")
    op.create_foreign_key(
        op.f("tracked_pages_user_id_fkey"), "tracked_pages", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "snapshots", type_="foreignkey")
    op.create_foreign_key(
        op.f("snapshots_tracked_page_id_fkey"),
        "snapshots",
        "tracked_pages",
        ["tracked_page_id"],
        ["id"],
    )
    # ### end Alembic commands ###
