"""add requires_js

Revision ID: ea7d1847a2c9
Revises: d0e9e408e3c4
Create Date: 2026-09-02 15:00:26.336607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea7d1847a2c9"
down_revision: str | Sequence[str] | None = "d0e9e408e3c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_pages",
        sa.Column("requires_js", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_pages", "requires_js")
    # ### end Alembic commands ###
